top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/arch/win32
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/arch/win32
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/arch/win32
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
