top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/aaa
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/aaa
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/aaa

include $(top_srcdir)/build/special.mk

