top_srcdir   = /home/mbin96/build/src/term/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/httpd-2.0.63/srclib
builddir     = /home/mbin96/build/src/term/httpd-2.0.63/srclib
VPATH        = /home/mbin96/build/src/term/httpd-2.0.63/srclib

SUBDIRS = pcre
BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
