top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
