top_srcdir   = /home/mbin96/build/src/term/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/httpd-2.0.63/modules/http
builddir     = /home/mbin96/build/src/term/httpd-2.0.63/modules/http
VPATH        = /home/mbin96/build/src/term/httpd-2.0.63/modules/http

include $(top_srcdir)/build/special.mk

