top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/mappers
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/mappers
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/modules/mappers

include $(top_srcdir)/build/special.mk

