#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','l','i','n','u',
        'x','-','g','c','c',' ','-','I','.',' ','-','I','.','.',' ','-','I','.',
        '.','/','i','n','c','l','u','d','e',' ',' ','-','D','O','P','E','N','S',
        'S','L','_','T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N',
        'T','R','A','N','T',' ','-','D','D','S','O','_','D','L','F','C','N',' ',
        '-','D','H','A','V','E','_','D','L','F','C','N','_','H',' ','-','s','t',
        'a','t','i','c',' ','-','O','3',' ','-','f','o','m','i','t','-','f','r',
        'a','m','e','-','p','o','i','n','t','e','r',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-generic32"
    #define DATE "built on: Thu Dec  5 13:40:27 2019"
#endif
