top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/os
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/os
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
