top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/os/unix
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/os/unix
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
