top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/os/beos
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/os/beos
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/os/beos

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = os.c beosd.c

include $(top_srcdir)/build/ltlib.mk
