top_srcdir   = /home/mbin96/build/src/term/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/httpd-2.0.63/modules/loggers
builddir     = /home/mbin96/build/src/term/httpd-2.0.63/modules/loggers
VPATH        = /home/mbin96/build/src/term/httpd-2.0.63/modules/loggers

include $(top_srcdir)/build/special.mk

