top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm/prefork
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm/prefork
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
