top_srcdir   = /home/mbin96/build/src/term/http/httpd-2.0.63
top_builddir = /home/mbin96/build/src/term/http/httpd-2.0.63
srcdir       = /home/mbin96/build/src/term/http/httpd-2.0.63/os/os2
builddir     = /home/mbin96/build/src/term/http/httpd-2.0.63/os/os2
VPATH        = /home/mbin96/build/src/term/http/httpd-2.0.63/os/os2

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = util_os2.c

include $(top_srcdir)/build/ltlib.mk
